Admin Remix New MonoRepo Create
git-goods/git-animal-client pull request #120
Opened 2024-07-13 14:44 UTC by sumi-0011

# 💡 기능
- 여러 어드민 관련 로직들을 처리하기 위해 어드민 페이지를 만들려고 하였어요. (내부적으로 사용하기 위해 간단하게)
- Next.js가 편하긴 하지만, 새로운 도전을 해보기 위해 @hyesungoh 추천을 받아 Remix로 세팅하였습니다. 

- Remix 설치 (기본적으로 제공하는 tailwind 제거)
- panda css 설치 (공통적으로 사용하는 theme 적용)
- shadow panda 연결
- turbo repo 연결 `pnpm dev:admin` 명령어로 실행 가능
- packages 들의 tsconfig, eslint 연결

# 🔎 기타
> @hyesungoh  Mono Repo 설정들을 이미 잘 해두어주셔서 큰 어려움 없이 세팅할 수 있었어요. 감사합니다!

2024-07-14 09:30 UTC, hyesungoh requested changes
`pnpm-workspace.yaml` 파일에도 추가해야 정상 실행될 거 같아요~

2024-07-14 13:48 UTC, sumi-0011 commented
> `pnpm-workspace.yaml` 파일에도 추가해야 정상 실행될 거 같아요~

추가하였습니다!
해당 파일에 추가하면, 루트에서 `pnpm i` 등을 실행할 때 admin 프로젝트 들의 `panda codegen`을 같이 실행할 수 있게 되는걸까요/>?

2024-07-15 14:39 UTC, hyesungoh commented
> > `pnpm-workspace.yaml` 파일에도 추가해야 정상 실행될 거 같아요~
> 
> 추가하였습니다! 해당 파일에 추가하면, 루트에서 `pnpm i` 등을 실행할 때 admin 프로젝트 들의 `panda codegen`을 같이 실행할 수 있게 되는걸까요/>?

정확히는 패키지 매니저가 모노레포 상의 패키지로 인식해용

pnpm i > panda codegen이 실행되는건 터보레포 파이프라인 떄문입니당

2024-07-15 14:39 UTC, hyesungoh approved these changes

2024-07-15 14:40 UTC, merged