feat: toss의 async boundary를 wrapper한 SEBoundary 생성
git-goods/git-animal-client pull request #141
Opened 2024-07-24 15:46 UTC by sumi-0011

# 💡 기능
- SEBoundary : Suspense Error Boundary
- 함수형으로 ErrorBoundary를 사용하고, 보통 Suspense와 같이 사용하기 때문에, toss의 async boundary를 래핑하여 간단하게 구현하였습니다.

2024-07-24 23:25 UTC, hyesungoh requested changes
현재는 웹 패키지 안에서만 SE바운더리를 사용할 수 있는데,

`@gitanimals/SEBoundary` 형태로 각 앱에서 사용할 수 있는 형태면 어떨까요?

> @gitanimals/SEBoundary가 @toss/async-boundary를 의존하고 있는 형태로요!

---

그리고 ... 사실 SEBoundary라는 이름이 직관적인가? 라고 물은다면 전 잘 모르겠습니다 ㅋㅋㅋㅋ

`@gitanimals/async-boundary`도 괜찮을 거 같은데, SEBoundary 라는 이름을 생각하신 배경이 궁금해요!!

2024-07-24 23:25 UTC, hyesungoh commented on apps/web/src/components/SEBoundary/SEBoundary.tsx
> +function SEBoundary({ pendingFallback, rejectedFallback, ...props }: SEBoundaryProps) {
```suggestion
function SEBoundary({ pendingFallback = INIT_PENDING_FALLBACK, rejectedFallback = INIT_ERROR_FALLBACK, ...props }: SEBoundaryProps) {
```

요롷게 기본 값으로 넣어주면 어떨까요 ??

의미에 더 부합하는 문법이라 생각돼서요 🤔

2024-07-24 23:25 UTC, hyesungoh commented on apps/web/src/components/SEBoundary/SEBoundary.tsx
> +const INIT_ERROR_FALLBACK = () => null;
ERROR_FALLBACK도 마찬가지로 `INIT_REJECTED_FALLBACK`으로 네이밍하면 어떨까요?? 🤔

2024-07-25 01:34 UTC, sumi-0011 commented
> 현재는 웹 패키지 안에서만 SE바운더리를 사용할 수 있는데,
> 
> `@gitanimals/SEBoundary` 형태로 각 앱에서 사용할 수 있는 형태면 어떨까요?
> 
> > @gitanimals/SEBoundary가 @toss/async-boundary를 의존하고 있는 형태로요!
> 
> 그리고 ... 사실 SEBoundary라는 이름이 직관적인가? 라고 물은다면 전 잘 모르겠습니다 ㅋㅋㅋㅋ
> 
> `@gitanimals/async-boundary`도 괜찮을 거 같은데, SEBoundary 라는 이름을 생각하신 배경이 궁금해요!!

기존에 라이브러리에서 주는 AsynceBoundary와 다른이름으로 지으려다 보니, SEBoundray로 작성했습니다 (import가 불편할것같아)

그런데 제안해주신 것과 같이 패키지로 따로 뺀다면 해결되는 문제인것 같아요!
추가적으로 패키지에 AsyncBoudary 컴포넌트만이 아닌, ErrorBoundary 관련 라이브러리도 설치해서 래핑 or 그냥 내보내기 해도 좋을 것 같아요
같은 패키지에 넣으면 좋을 것 같다고 생각한 추가적인 라이브러리는 아래와 같아요! 
- https://www.slash.page/ko/libraries/react/error-boundary/src/ErrorBoundary.i18n
- https://www.slash.page/ko/libraries/react/async-boundary/src/withAsyncBoundary.i18n

2024-09-13 13:49 UTC, closed without merging

2024-09-13 13:50 UTC, sumi-0011 commented
이부분은 필요없을것 같아 닫습니다 .
에러바운더리는 이후에 다시 추가해볼게요