sonnar 라이브러리 추가 및 공지사항 toast 추가
git-goods/git-animal-client pull request #166
Opened 2024-08-28 07:41 UTC by sumi-0011

# 💡 기능
- sonnar 라이브러리를 추가하여 토스트 메시지를 구현하였습니다. 
- 토스트 메시지를 이용하여 공지사항을 보여줄 수 있도록 하였습니다 -> 이후에는 디비나 로컬 json을 읽어 공지사항을 띄울 수 있도록 하면 좋을 것 같아요
- 공지사항은 auth 여부에 따라, 그리고 한번 토스트를 끄지 않는 이상 계속해서 보여집니다 (local storage로 체크)
- 아직 특정 유저에게만 보여준다거나 하는 공지가 없기 때문에 디비/서버연결은 불필요하다고 생각하였어요
- 무조건 한번만 토스트를 띄우기 위해 `AbordContoller`와 `performCancellableAsyncTask` 라는 메소드를 구현하여 사용하였어요. (useEffect 두번 실행을 막기 위햬)

---
참고 : https://velog.io/@sumi-0011/useEffect-two

2024-08-28 11:24 UTC, hyesungoh requested changes

2024-08-28 11:24 UTC, hyesungoh commented on apps/web/src/app/dev/Client.tsx
> +          <Button onClick={() => toast('asdadsasd')}>Toast</Button>
여기 테스트 코드가 남아있어여

2024-08-28 11:24 UTC, hyesungoh commented on apps/web/src/components/NoticeToast/NoticeToast.tsx
> +    });
말씀하신것처럼 한 번만 실행하기 위함이라면, ref를 이용해도 구현할 수 있을 거 같은데

요롷게 하신 이유가 궁금해용

어보트 컨트롤러는 아는데, 아래쓰인 api는 처음봐요!! 알려주세용

2024-08-28 14:21 UTC, sumi-0011 commented on apps/web/src/components/NoticeToast/NoticeToast.tsx
> +    });
performCancellableAsyncTask 이거 제가 만든거예요! 
참고한 링크는 [여기](https://medium.com/@tangiblej/cancel-a-promise-inside-react-useeffect-12a101606b72)입니당

ref를 사용하는건 정말 생각도 못했네요... 왜지..??
너무 코드에 갇혀있었나봐요 🤔

오버엔지니어링은 맞아서 ref를 사용한 방식으로 변경하는게 좋을것 같네요!

2024-08-28 14:31 UTC, hyesungoh commented on apps/web/src/components/NoticeToast/NoticeToast.tsx
> +    });
아하 이름만 보고 web api인 줄 알았어요 ㅋㅋㅋㅋ 👍 👍 

https://github.com/imbhargav5/rooks/blob/main/packages/rooks/src/hooks/useDidMount.ts

제가 개인적으로 참고했던 구현은 위와 같아요!

> 근데 effect를 통해 이전의 life cycle 동작을 흉내내는 것 같아서, useEffectOnce 이런 이름도 잘 어울릴 거 같다는 생각이예용 🤔

2024-08-28 14:32 UTC, hyesungoh commented on packages/util/common/src/abort/performCancellableAsyncTask.ts
요 유틸은 window가 없을 때 방어 로직이 있을 법도 한 거 같은데,

어떻게 생각하시나요 🤔 🤔 🤔 🤔 🤔

2024-08-28 14:36 UTC, hyesungoh commented on apps/web/src/components/NoticeToast/NoticeToast.tsx
> +    });
개인적은 취향은 그렇습니다 ~~

2024-08-28 14:38 UTC, sumi-0011 commented on packages/util/common/src/abort/performCancellableAsyncTask.ts
그러네요 이벤트 리스너를 등록하는 로직이 있다보니 window가 필수있것 같아요. 
상단에 넣도록 하겠습니다! 감사합니다~

2024-08-29 06:17 UTC, hyesungoh commented on apps/web/src/hooks/lifeCycle/useEffectOnce.ts
1. 요거는 `packages/` 하위에 있으면 오똘까나요??


2. 테스트 코드도 작성해보시면 좋을 거 같아요 ~~~

2024-08-29 06:18 UTC, sumi-0011 commented on apps/web/src/hooks/lifeCycle/useEffectOnce.ts
네! 좋아요 :D
이부분은 패키지도 새로 파야하고 `/pacakges/hooks` 하다보니 이후 PR에서 진행하겠습니다!

2024-08-29 06:18 UTC, merged