Select UI 추가
git-goods/git-animal-client pull request #58
Opened 2024-06-18 06:14 UTC by sumi-0011

# 💡 기능
- Select UI 컴포넌트를 추가하였습니다. 
- 아직은 Feedback 컴포넌트에서만 사용될 예정이므로 components/FeedBack 폴더 내에 만들어 두었습니다. 이후에 ui pacakges를 만들거나 재사용하는 경우가 생기면 옮기면 될 것 같습니다. 
- panda css가 아직 적용되지 않은 상태이므로 일단 styled-component를 이용해서 구현하였습니다. 이후 마이그레이션할 예정입니다. 
- headless 를 참고하여 만들어봤어요. [링크](https://headlessui.com/react/select)
# 🔎 기타
<img width="226" alt="image" src="https://github.com/git-goods/git-animal-client/assets/49177223/fba4bb74-b7de-4928-8c7b-92609d9b9fd4">

2024-06-18 07:06 UTC, hyesungoh requested changes
`컴포넌트/피드백/셀렉트`

라는 위계가 살짝 어색한데요 🤔 

---

피드백은 도메인이 포함된 기능으로 보이고

셀렉트는 도메인이 없는 말씀하신 헤드리스한, 컴포넌트로 보여요

---

셀렉트는 다양한 도메인에서 사용할 수 있는 셀렉트로 두고,

이를 사용한 피드백 셀렉트, 혹은 피드백을 만들면 어떨까요?

2024-06-18 07:37 UTC, sumi-0011 commented
> `컴포넌트/피드백/셀렉트`
> 
> 라는 위계가 살짝 어색한데요 🤔
> 
> 피드백은 도메인이 포함된 기능으로 보이고
> 
> 셀렉트는 도메인이 없는 말씀하신 헤드리스한, 컴포넌트로 보여요
> 
> 셀렉트는 다양한 도메인에서 사용할 수 있는 셀렉트로 두고,
> 
> 이를 사용한 피드백 셀렉트, 혹은 피드백을 만들면 어떨까요?

폴더 위치 수정했습니다!

2024-06-18 09:49 UTC, hyesungoh approved these changes
고생하셨어요 👍 👍 마이너한 코멘트만 남겨봤어용

2024-06-18 09:49 UTC, hyesungoh commented on apps/web/src/components/Select/Root.tsx
> +const SelectOpenContext = React.createContext<SelectOpenContextProps>({
요기도 그냥 `createContext`를 임포트해서 사용하면 어떨까요??

createContext만 요롷게 하신 이유가 궁금해요!!

2024-06-18 09:49 UTC, hyesungoh commented on apps/web/src/components/Select/Option.tsx
> +}
아이콘은 추후 리팩터링이 필요하긴 하겠네요 🤔

2024-06-19 02:51 UTC, sumi-0011 commented on apps/web/src/components/Select/Option.tsx
> +}
맞아요! 따로 icon pacakges를 팔려고 일단 냅두었습니다
어떻게 할까요..고민이 많아지다보니 딜레이가 되네요...

2024-06-19 02:52 UTC, sumi-0011 commented on apps/web/src/components/Select/Root.tsx
> +const SelectOpenContext = React.createContext<SelectOpenContextProps>({
사실 별 이유는 없었고 수정하고 머지하겠습니다!

2024-06-19 02:53 UTC, merged