TextArea UI 컴포넌트 추가
git-goods/git-animal-client pull request #61
Opened 2024-06-18 07:56 UTC by sumi-0011

# 💡 기능
- textarea 컴포넌트를 추가하였습니다. 
- error는 일단 ui를 위해 boolean props를 받도록 하였어요. 이후에 textarea를 어떻게 사용하느냐에 따라 error props를 string으로 받을 수도 있을 것 같아요 (error message용)
# 🔎 기타
<img width="223" alt="image" src="https://github.com/git-goods/git-animal-client/assets/49177223/3f5bb40f-de3a-43f7-8af0-1f5c43be349b">

2024-06-18 09:58 UTC, hyesungoh requested changes

2024-06-18 09:58 UTC, hyesungoh commented on apps/web/src/components/TextArea.tsx
> +interface TextAreaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
Input 컴포넌트 작업하신 것처럼 `ComponentProps<'textarea'>`로 하면 좋을 거 같아요 ~

> 타입이 더 정확하더라고 합디다

2024-06-18 09:58 UTC, hyesungoh commented on apps/web/src/components/TextArea.tsx
> +  const onChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
`React.` 보다는 직접 임포트하는게 어떨까나요??

2024-06-18 09:58 UTC, hyesungoh commented on apps/web/src/components/TextArea.tsx
> +    props.onChange && props.onChange(e);
```suggestion
    props?.onChange?.(e);
```

옵셔널 체이닝으로 축약할 수 있을 거 같아요 ~

2024-06-18 09:58 UTC, hyesungoh commented on apps/web/src/components/TextArea.tsx
> +};
요 구문은

```
({maxLength = 300, ...props })
```
이렇게도 작성할 수 있을 거 같은데, 요롷게 작성하신 이유가 궁금해요~

2024-06-18 09:58 UTC, hyesungoh commented on apps/web/src/components/TextArea.tsx
> +  $error?: boolean;
$ (달라 사인)을 사용하신 이유가 궁금해용

2024-06-19 02:56 UTC, sumi-0011 commented on apps/web/src/components/TextArea.tsx
> +};
위처럼 작성하면 maxLength는 props로 묶을 수 없어서 defaultProps로 작성해둔것이긴 해요. 
`({maxLength = 300, ...props })` 이렇게 작성하는게 더 최신 방법인것으로 알고있는데 이 방식을 사용하는 게 더 좋을까요?

2024-06-19 03:02 UTC, sumi-0011 commented on apps/web/src/components/TextArea.tsx
> +  $error?: boolean;
styling만을 위한 props를 넘길 때 html 태그에 영향이 가지 않도록 지정하기 위해서 사용하였어요!
이전까지는 해당 부분에 큰 문제를 못느껴 error 이런식으로 사용했었는데, 회사에서 이러한 코드들이 쌓이다보니, html tag랑 겹친다 하는 console error가 발생하는 것을 보았습니다. 
이후 부터는 이런식으로 작성하고있어요! (스타일을 위한 props에만 $를 붙이고 있습니다)

참고 : https://velog.io/@haru/styled-components-props-error

2024-06-19 03:03 UTC, sumi-0011 commented on apps/web/src/components/TextArea.tsx
> +  $error?: boolean;
fyi) 저희가 사용하는 styled-component version은 6버전 입니다.

2024-06-19 05:44 UTC, hyesungoh commented on apps/web/src/components/TextArea.tsx
> +  $error?: boolean;
얍얍 👍 판다로 이관하면 컨벤션으로 삼지 않아도 될 거 같네용 👍

2024-06-19 05:45 UTC, hyesungoh commented on apps/web/src/components/TextArea.tsx
> +};
작성해주신 방법은 props에 대한 관심사가 멀어진 느낌으로 다가와서, 

선호되진 않는 거 같아용

수미칩은 어떻게 생각하셔요?? 🤔

2024-06-19 06:10 UTC, sumi-0011 commented on apps/web/src/components/TextArea.tsx
> +};
props의 관심사 쪽을 생각을 못했네요  🤔
한눈에 알아볼 수 있도록 수정했습니다!

2024-06-19 06:12 UTC, hyesungoh requested changes

2024-06-19 06:12 UTC, hyesungoh commented on apps/web/src/components/TextArea.tsx
> +      <TextAreaStyled {...props} onChange={onChange} />
아 여기에 maxLength 들어가야될거같아용

2024-06-19 06:13 UTC, sumi-0011 commented on apps/web/src/components/TextArea.tsx
> +      <TextAreaStyled {...props} onChange={onChange} />
와오

2024-06-19 06:14 UTC, sumi-0011 commented on apps/web/src/components/TextArea.tsx
> +      <TextAreaStyled {...props} onChange={onChange} />
수정하였습니다~ 감사합니다!

2024-06-19 06:21 UTC, hyesungoh approved these changes
🧃 🧃 🧃 🧃

2024-06-19 06:31 UTC, merged